inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'camper.gemspec'
    - 'lib/camper/core_extensions/object.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/camper/client/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/camper/*'
    - 'lib/camper/api/*'
    - 'lib/camper/resources/*'

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false